language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "14"
script:
  - npm run test && npm run build
after_success:
  - npm run report-coverage
  # - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run semantic-release; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
